---
- hosts: ubuntu
  gather_facts: yes
  become: yes
  vars:
   - web_dir: /var/www/test.www/web
  tasks:
   - name: Install Apache
     apt: name=apache2 state=present
     notify:
      - start apache
   - name: create directory
     file: path={{ web_dir }} mode=775 state=directory owner=ansible group=ansible
     notify:
      - restart apache
  handlers:
   - name: start apache
     service: name=apache2 state=started
   - name: restart apache
     service: name=apache2 state=restarted
