---
- hosts: webserver
  become: yes
  gather_facts: yes
  tasks:
   - name: install apache on rhel box
     yum: name=httpd state=present
     when: ansible_os_family == 'RedHat'
   - name: install apache on ubuntu box
     apt: name=apache2 state=present
     when: ansible_os_family == 'Ubuntu'
   - name: start and enable apache on rhel box
     service: name=httpd state=started enabled=yes
     when: ansible_os_family == 'RedHat'
   - name: start amd enable apache on Ubuntu
     service: name=apache2 state=started enabled=yes
     when: ansible_os_family == 'Ubuntu'
