---
- hosts: dbserver
  become: yes
  gather_facts: no
  tasks: 
    - name: create group
      group:
        name: ansiblegrp
    - name: create multiple user
      user:
        name: "{{ item.uname }}"
        uid: "{{ item.userid }}"
        state: present
        group: ansiblegrp
      with_items:
        - { uname: 'user1', userid: 5001 }
        - { uname: 'user2', userid: 5005 } 
