---
- hosts: 192.168.1.10
  become: yes
  gather_facts: yes
  tasks:
   - name: install apache on ubuntu box
     apt: name=apache2 state=present
     #when: ansible_os_family == 'Ubuntu'
   - name: start amd enable apache on Ubuntu
     service: name=apache2 state=started enabled=yes
     #when: ansible_os_family == 'Ubuntu'

