---
- hosts: dbserver
  become: yes
  gather_facts: no
  vars:
    passwd: $6$HW3NugZa$HrJHy/1Zv4cDi1oCa7pltvdAln/kojM8J5atzGjUEWaCWSHYKXI7vYku1iQn5feldxQ5lQh2HnClttha2Zcj/1 
  tasks:
    - name: create group
      group:
        name: ansiblegrp
    - name: create user
      user:
        name: "{{ item }}"
        group: ansiblegrp
        state: present
        password: "{{ passwd }}"
      with_items:
        - test1
        - test2
    
